Update flutter_datetime_picker.dart
datetime_picker_theme.dart collides with definition of DatePickerTheme in material.dart, we must hide the DatePickerTheme from material to avoid :
Error: 'DatePickerTheme' is imported from both 'package:flutter/src/material/date_picker_theme.dart' and 'package:flutter_datetime_picker/src/datetime_picker_theme.dart'.